<a href="https://colab.research.google.com/github/Ishan-sharma8/NUMPY/blob/main/Creating_numpy_array_using_arange_and_linspace.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
b = np.arange(2, 20, 2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
b = np.linspace(2, 10)
print(b[1] - b[0])
print(b[3] - b[2])
b

0.16326530612244916
0.16326530612244916


array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [8]:
b = np.linspace(2, 12, 5, dtype = int, endpoint = False)
b

array([ 2,  4,  6,  8, 10])

In [11]:
c = np.identity(4)
print(c)
d = np.eye(3, 4)
d

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [13]:
a = np.random.rand(4)
a

array([0.66829164, 0.19119769, 0.80465189, 0.07294728])

In [14]:
a = np.random.rand(10)*10
a

array([4.97635664, 9.08832566, 7.2310169 , 4.96797038, 9.51077898,
       0.73940357, 7.12034373, 1.11819519, 9.2445988 , 2.21480426])

In [15]:
a = np.random.rand(2, 3)
a

array([[0.12799476, 0.70458707, 0.50115977],
       [0.55961048, 0.29576173, 0.12396264]])