<a href="https://colab.research.google.com/github/Ishan-sharma8/NUMPY/blob/main/Mathematical_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.random.randint(1,20,5)
b=np.random.randint(1,20,5)
li=[1,2,3,4,5]
print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[12  3  1 17 11]
[15 17  3 11  1]


In [ ]:
li=[i+1 for i in li]
li
a=a+1


In [ ]:
print(a.sum())  #similarly mean,min,argmin,max

49


In [ ]:
a>b

array([False, False, False,  True,  True])

In [ ]:
print(np.logical_and(a,b))

[ True  True  True  True  True]
