<a href="https://colab.research.google.com/github/Ishan-sharma8/NUMPY/blob/main/Numpy_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a=[1,2,3]
b=np.array(a)
print(b)
print(type(b)) 


[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
c=[1,2,3,'5','a',4.5]  #adding few strings ;in a 3 integers,2 strings and 1 float
d=np.array(c)# in d every element is of strings
print(d)

['1' '2' '3' '5' 'a' '4.5']


In [5]:
c=[1,2,3,'5',4.5]
d=np.array(c,dtype=int)
e=np.array(c,dtype=float)
print(d)
print(e)


[1 2 3 5 4]
[1.  2.  3.  5.  4.5]


In [9]:
f=np.array(c  *3)
f
print(f)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


In [29]:
w=np.ones(3,dtype=int)
x=np.zeros(3)
y=np.full(3,4)
z=np.empty(3)
print(w)
print(x)
print(y)
print(z)

[1 1 1]
[0. 0. 0.]
[4 4 4]
[2.e-323 2.e-323 2.e-323]


In [27]:
p=np.ones((2,3),dtype=int) 
q=np.zeros((3,4),dtype=int) 
r=np.full((3,4),5,dtype=float)
print(p)
print(q)
print(r)

[[1 1 1]
 [1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
